"use client";

import { useEffect, useState } from "react";

type Featured = { id: string; slug: string; name: string; quest_title: string; published: boolean; display_order: number };
const blank = { slug: "", name: "", gender: "", species: "", occupation: "", appearance: "", personality: "", roleplaying_cue: "", quest_title: "", quest_hook: "", full_adventure: "", portrait_url: "", character_card_url: "", clean_video_url: "", youtube_video_id: "", display_order: 0 };

export default function FeaturedManager() {
  const [items, setItems] = useState<Featured[]>([]);
  const [form, setForm] = useState(blank);
  const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/admin/featured"); const data = await response.json(); if (response.ok) setItems(data.items); else setMessage(data.error); }
  useEffect(() => { void load(); }, []);
  async function save() { const response = await fetch("/api/admin/featured", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, appearance: form.appearance.split(",").map((value) => value.trim()).filter(Boolean) }) }); const data = await response.json(); setMessage(data.error || (response.ok ? "Featured NPC added." : "Save failed.")); if (response.ok) { setForm(blank); void load(); } }
  async function upload(field: "portrait_url" | "character_card_url" | "clean_video_url", file: File) { const body = new FormData(); body.append("file", file); body.append("bucket", "featured-media"); const response = await fetch("/api/admin/featured/upload", { method: "POST", body }); const data = await response.json(); if (response.ok) setForm((current) => ({ ...current, [field]: data.url })); setMessage(data.error || (response.ok ? "Media uploaded." : "Upload failed.")); }
  async function publish(item: Featured) { const response = await fetch("/api/admin/featured", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: item.id, published: !item.published }) }); const data = await response.json(); setMessage(data.error || (response.ok ? "Updated." : "Update failed.")); if (response.ok) void load(); }
  return <main className="min-h-screen bg-[#171008] p-6 text-[#f4e4bf]"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#d7b775]">Guildmaster Tools</p><h1 className="mt-2 font-serif text-4xl font-bold">Featured NPC Library</h1><p className="mt-2 text-[#cdbb94]">Add unpublished characters and publish them when their media package is ready.</p>{message && <p className="mt-4 border border-[#8d6b2c] p-3">{message}</p>}<section className="mt-6 grid gap-3 border border-[#6e5428] bg-[#20170d] p-5 md:grid-cols-2">{Object.entries(form).map(([key, value]) => <label key={key} className="text-xs font-bold uppercase tracking-wide text-[#d7b775]">{key.replaceAll("_", " ")}<textarea className="mt-1 min-h-10 w-full border border-[#8d6b2c] bg-[#f1e4ca] p-2 font-normal normal-case text-[#281b12]" value={String(value)} onChange={event => setForm({ ...form, [key]: key === "display_order" ? Number(event.target.value) : event.target.value })} /></label>)}<div className="md:col-span-2 grid gap-3 sm:grid-cols-3">{([["portrait_url", "Portrait"], ["character_card_url", "Character Card"], ["clean_video_url", "Clean Video"]] as const).map(([field, label]) => <label key={field} className="border border-[#8d6b2c] p-3 text-xs font-bold uppercase text-[#d7b775]">Upload {label}<input type="file" className="mt-2 block w-full text-xs" onChange={event => { const file = event.target.files?.[0]; if (file) void upload(field, file); }} /></label>)}</div><button onClick={save} className="border border-[#b88a32] bg-[#b88a32] px-4 py-3 font-bold uppercase tracking-wide text-[#171008]">Add Featured NPC</button></section><div className="mt-8 space-y-3">{items.map(item => <article key={item.id} className="flex flex-wrap items-center justify-between gap-4 border border-[#6e5428] bg-[#20170d] p-4"><div><h2 className="font-serif text-xl font-bold">{item.name}</h2><p className="text-sm text-[#cdbb94]">{item.quest_title} · order {item.display_order}</p></div><button onClick={() => publish(item)} className="border border-[#b88a32] px-3 py-2 text-xs font-bold uppercase">{item.published ? "Unpublish" : "Publish"}</button></article>)}</div></div></main>;
}
